# Generated by Django 5.1.6 on 2025-02-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=12, null=True)),
                ('foto', models.ImageField(upload_to='fotos')),
                ('pagamento', models.BooleanField(default=True)),
                ('queixa', models.CharField(choices=[('TDAH', 'TDAH'), ('BORDERLINE', 'BORDERLINE'), ('DEPRESSÃO', 'DEPRESSÃO')], max_length=10)),
            ],
        ),
    ]
