# Generated by Django 5.0.6 on 2025-02-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='queixa',
            field=models.CharField(choices=[('TDAH', 'TDAH'), ('BORDERLINE', 'BORDERLINE'), ('DEPRESSAO', 'DEPRESSÃO')], max_length=10),
        ),
    ]
